### ISSUE TITLE
Touching buttons on hike screen for smaller screens

### ISSUE THREAD

**Issue by ItsAdityaKSingh** [CCExtractor/beacon#104]
**Describe the bug**
Buttons on hike screen are too close for small screen sizes

**To Reproduce**

1. Go to 'Hike Screen'
2. See error

**Expected behavior**
The buttons should not touch or overlap

**Demonstration**
<img src="https://user-images.githubusercontent.com/69353350/151605778-f400ae89-276c-46b6-b401-87e3892ed5f3.png" height="500"/>

**Environment**
- Device/emulator being used: Pixel 2
- OS (iOS/ Android); If Android then android version: <OS: 10>
- Flutter version: 2.8.1

**Are you working on this issue? (Yes/No)**
Yes

**Comment by Omegaviv** [comment]
is anyone working on this?
