### ISSUE TITLE
Migrating Deprecated Widgets and Removing unused imports.

### ISSUE THREAD

**Issue by Aadeesh11** [CCExtractor/beacon#11]
- FlatButton should not be used, instead use TextButton.
- Remove multiple unused imports.

I would like to work on this issue, please assign it to me.

**Comment by Divijkatyal0406** [comment]
Hi! Is the app running on your system? I am facing build failures.
<img width="960" alt="help" src="https://user-images.githubusercontent.com/81143854/147409932-91200a2c-b13c-478d-91f1-b8ca6cbe4d2a.png">

**Comment by nb9960** [comment]
Thanks for opening the issue, assigning it to you!  @Aadeesh11

**Comment by Aadeesh11** [comment]
> Hi! Is the app running on your system? I am facing build failures. <img alt="help" width="960" src="https://user-images.githubusercontent.com/81143854/147409932-91200a2c-b13c-478d-91f1-b8ca6cbe4d2a.png">

Yes the app is running in my local system, though i had to make few changes.
PR #9 would probably fix this.
