### ISSUE TITLE
Logout Dialog is not rounded like other dialogs in the app.

### ISSUE THREAD

**Issue by Pavel401** [CCExtractor/beacon#110]
**Describe the bug**
AlertDialog Typically used in conjunction with [showDialog].

**To Reproduce**
Open App>FloatingActionButton>DiaLog

**Expected behavior**
AlertDialog should have a shape and contentPadding.
**Demonstration**
Before            |  After
:-------------------------:|:-------------------------:
![27e0e8cb-80a8-4671-a372-a10ffbeb5f26](https://user-images.githubusercontent.com/47685150/152035370-51e757ba-87b8-482d-941d-7fa94e29dee2.jpg) | ![05eab1c0-1d37-468b-8ebd-228aa5b70e0c](https://user-images.githubusercontent.com/47685150/152035391-2109968c-e637-4eea-8f45-b8616ad3e8e6.jpg)

**Environment**
- Device/emulator being used: <device version/emulator>
- OS (iOS/ Android); If Android then android version: <OS: OS version>
- Flutter version: <2.8>

**Are you working on this issue? (Yes/No)**
Yes

**Comment by somendrakr** [comment]
Is this issue is still open. if yes can i work on it.

**Comment by codewithkushagra** [comment]
I want have resolved this issue, can I make the pr for the same?

**Comment by pnkr01** [comment]
Is this issue resolved and merged??

**Comment by aks-2101** [comment]
Is this issue available? I want to work on this.

**Comment by Pavel401** [comment]
> @Pavel401 Is this issue available? I want to work on this.

https://github.com/CCExtractor/beacon/pull/161
It's already fixed.

**Comment by Pavel401** [comment]
> @Pavel401 Is this issue available? I want to work on this.

https://github.com/CCExtractor/beacon/pull/161
It's already fixed.
