### ISSUE TITLE
Build Failure!

### ISSUE THREAD

**Issue by Divijkatyal0406** [CCExtractor/beacon#12]
Hi! I am new to open source contribution. I forked the repository and ran the app in debug mode on my system but build failed and I am unable to understand what's the cause behind it. Someone please help!
I have attached the description of error.
<img width="960" alt="help" src="https://user-images.githubusercontent.com/81143854/147409482-5d47ed52-0d8e-45ef-86c0-adf95adde707.png">

**Comment by nb9960** [comment]
You've not entered the `MAPS_API_KEY` in .env file. Make sure to go through the setup instructions in README.md

**Comment by Divijkatyal0406** [comment]
Yeah I added that in a new .env file but still error persists.
