### ISSUE TITLE
Beacon list reloads each time State is updated

### ISSUE THREAD

**Issue by ItsAdityaKSingh** [CCExtractor/beacon#120]
**Describe the bug**
The beacon list on the home screen reloads each time when the state is updated

**To Reproduce**

1. Go to 'Home Screen'
2. Click on 'Create/Join'
3. Click on any text field

**Expected behavior**
The widget should be built once the screen has been built. Reloading shouldn't happen every time state chages.

**Demonstration**

https://user-images.githubusercontent.com/69353350/152697651-a50d0134-0065-4574-9692-8b4c32f9f215.mov

**Environment**
- Device/emulator being used: Pixel 4a XL
- OS (iOS/ Android); If Android then android version: <OS: 10>
- Flutter version: 2.10

**Are you working on this issue? (Yes/No)**
Yes

**Comment by AliAkberAakash** [comment]
Is this available?

**Comment by ItsAdityaKSingh** [comment]
Gonna make a PR soon for this. A little delayed due to academics. If not resolved, you may see this through @AliAkberAakash :)
