### ISSUE TITLE
Feature Request: Reactivate Beacon after it has expired on leader's demand.

### ISSUE THREAD

**Issue by Aadeesh11** [CCExtractor/beacon#126]
**Is your feature request related to a problem? Please describe.**
Once a beacon has ended there is no way to reactivate, which sometimes can be a bad UX.

**Describe the solution you'd like**
Would like to allow  leader to reactivate an active beacon.

**Are you working on this? (Yes/No)**
Yes

**Comment by ItsAdityaKSingh** [comment]
Doesn't the app ask for a confirmation to deactivate a beacon? If a leader deactivates it, reactivating it again wouldn't seem like a genuine option afaik, and maybe bringing in this option would increase complexity. The beacon itself remains active until the leader wishes to terminate it.

**Comment by Aadeesh11** [comment]
Yes leader can change his mind , no?😅
Giving users option to reactivate a beacon saves a lot of time for the group, no sharing short code again , no multiple beacon on home screen.

**Comment by ItsAdityaKSingh** [comment]
Wouldn't that make users to keep on reactivating the same beacon again and again? XD
Also, for the respective feature you will have to edit it's details, a feature which is being taken care of in issue #107. Creating another issue with the same required changes wouldn't be necessary imo.

**Comment by Aadeesh11** [comment]
Yes they can keep reactivating it again and again, and save the hassle of creating a new one everytime. Closing this issue, since #107 handles.
