### ISSUE TITLE
Make placeholder text in "Your Beacons" interactable

### ISSUE THREAD

**Issue by devmrfitz** [CCExtractor/beacon#132]
**Is your feature request related to a problem? Please describe.**
When the app launches and _Your Beacons_ section is empty, the following screen is shown:
![image](https://user-images.githubusercontent.com/58381523/153235651-b73757ef-2057-422a-80d8-d180250cbc8b.png)
The circled buttons are yellow in colour and hence look interactable, but they aren't.

**Describe the solution you'd like**
Try to connect these words to their respective actions, similar to the actual buttons

**Are you working on this?**
Yes

**Comment by devmrfitz** [comment]
Thanks for you opinions @ItsAdityaKSingh. Sounds fair that the extra actions might get repetitive. But the text being yellow also prompts the user that it is interactable in some manner. To avoid confusion, should we make the yellow "create" and "join" text back to black?

**Comment by ItsAdityaKSingh** [comment]
I guess leaving them as they are would be better cause they were introduced in the first place for the same purpose of bettering UI. Regarding it or any further queries could be answered by @nb9960 :)

**Comment by nb9960** [comment]
Instead of making it actionable, turning it into bold black would be a better option to avoid confusion.
Also why this panel is overlapping in your screen, have you pulled the recent commits?

**Comment by devmrfitz** [comment]
@nb9960 I do have the latest commits. Maybe it's due to it being an emulator and not a physical device?

**Comment by ItsAdityaKSingh** [comment]
> @nb9960 I do have the latest commits. Maybe it's due to it being an emulator and not a physical device?

Maybe cause the sliding panel of your notifications panel is not quite what it should be like. It's a bit broader.
