### ISSUE TITLE
Resolve Splash deprecation warning

### ISSUE THREAD

**Issue by devmrfitz** [CCExtractor/beacon#133]
**Is your feature request related to a problem? Please describe.**
When building the app, the following warning is displayed:
`W/FlutterActivityAndFragmentDelegate(30068): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.`

@nb9960 Should I look into this?

**Are you working on this?**
Yes

**Comment by nb9960** [comment]
This issue is somewhat related to #58, you can comment there to get assigned if no one is working on it, closing this one for now.
