### ISSUE TITLE
Add Environment config file 

### ISSUE THREAD

**Issue by adarsh-technocrat** [CCExtractor/beacon#135]
**Describe the Issue**

The issue is currently we are calling this  `FlutterConfig.get(<Env Variable>)`   everywhere where it's needed. Instead, the proposed solution is to create a `class ` and declare these as static variables.  And also add **IOS Google Map API Key**  in **Env Variables** so that developers can test this app in both Android and IOS.

Thank You :)

 
 Cc: @nb9960  @Aadeesh11  @ItsAdityaKSingh

**Comment by nb9960** [comment]
Agreed with the fact that Google maps for iOS need to be configured.
With respect to the former part, sharing secret keys publicly is a bad practice, so this obviously shouldn't be done. One needs to fetch their own keys.
