### ISSUE TITLE
Outdated sdk 

### ISSUE THREAD

**Issue by Pavel401** [CCExtractor/beacon#139]
**Describe the bug**
During debugging many warnings are poping.

- Warning: The plugin flutter_local_notifications requires Android SDK version 31.
- Warning: The plugin path_provider_android requires Android SDK version 31.
- Warning: The plugin share_plus requires Android SDK version 31.
- Warning: The plugin url_launcher_android requires Android SDK version 31.
- Your project requires a newer version of the Kotlin Gradle plugin.      

**Expected behavior**
No errors should be there.
**Demonstration**
![depe](https://user-images.githubusercontent.com/47685150/153807230-b8e84ee9-8951-46aa-9631-ebf6aa93b5e3.png)
![kot](https://user-images.githubusercontent.com/47685150/153807229-46915a0c-dc82-44df-82ad-7005d4c1901f.png)

**Environment**
- Device/emulator being used: <device version/emulator>
- OS (iOS/ Android); If Android then android version: <OS: 11.0>
- Flutter version: <2.10>

**Are you working on this issue? (Yes/No)**
-Yes

**Comment by ItsAdityaKSingh** [comment]
Issue #118 also marks the same error. You would like to check it first :)
