### ISSUE TITLE
Update Hike Screen once a hike has ended

### ISSUE THREAD

**Issue by ItsAdityaKSingh** [CCExtractor/beacon#147]
**Describe the bug**
There's no update on the hike screen after a Hike is ended. 

**Expected behavior**
Screen should either get updated by itself after expiration of hike or should notify the users that the ***Hike has Expired***, and provide a ***Refresh*** button along to update the hike.

**Demonstration**

https://user-images.githubusercontent.com/69353350/157264564-c0c0c563-ffdf-4104-a0b8-f1e5b60b44f0.mov

**Environment**
- Device/emulator being used: Pixel 4XL
- OS (iOS/ Android); If Android then android version: <OS: 10>
- Flutter version: 2.10.1

**Are you working on this issue? (Yes/No)**
Yes, upon confirming the best choice to be implemented.

**Comment by ItsAdityaKSingh** [comment]
@nb9960 Would really appreciate your views on this :)

**Comment by nb9960** [comment]
Since this is somewhat related to #130 and can be dealt while solving that only, so closing this for now
