### ISSUE TITLE
Overflow issue on homescreen.

### ISSUE THREAD

**Issue by Aadeesh11** [CCExtractor/beacon#15]
Getting a overflow issue on Homescreen due to the 2 buttons.

![overflow](https://user-images.githubusercontent.com/66922161/147411713-fcbd2d48-2306-4d2a-88d8-965718ec777c.jpeg)

I would like to work on this, please assign it to me.

**Comment by nb9960** [comment]
Assigning it to you @Aadeesh11. I would suggest using [sizer](https://pub.dev/packages/sizer) for responsiveness.

**Comment by Aadeesh11** [comment]
I have already fixed the issue, but will have a look at sizer too.

**Comment by nb9960** [comment]
Yes, I just checked your commit, you have used constant values. It would be better to change it and make it responsive throughout using sizer as a good practice.

**Comment by Aadeesh11** [comment]
Ok, but the constant value is for the button height (that is the vertical padding) which is same regardless of the screen size, so how would i use sizer here? 🤔
