### ISSUE TITLE
Need to update `compileSdkVersion`  and  `targetSdkVersion`

### ISSUE THREAD

**Issue by AliAkberAakash** [CCExtractor/beacon#153]
**Describe the bug**
Currently the `compileSdkVersion` and `targetSdkVersion` are set to `30` and some plugins used require it to be latest (31). 

**To Reproduce**
Clone the repo and build it.

**Expected behavior**
Should build without any errors.

**Demonstration**
Stacktrace:
`Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Warning: The plugin flutter_local_notifications requires Android SDK version 31.
Warning: The plugin flutter_plugin_android_lifecycle requires Android SDK version 31.
Warning: The plugin geolocator_android requires Android SDK version 31.
Warning: The plugin google_maps_flutter requires Android SDK version 31.
Warning: The plugin path_provider_android requires Android SDK version 31.
Warning: The plugin share_plus requires Android SDK version 31.
Warning: The plugin shared_preferences_android requires Android SDK version 31.
Warning: The plugin url_launcher_android requires Android SDK version 31.
One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to /Users/bs274/flutter_projects/beacon/android/app/build.gradle:
android {
  compileSdkVersion 31
  ...
}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.window:window-java:1.0.0-beta04.
        AAR metadata file: /Users/bs274/.gradle/caches/transforms-2/files-2.1/49c20bb545c2ac1141397bf677f0fdc5/jetified-window-java-1.0.0-beta04/META-INF/com/android/build/gradle/aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.window:window:1.0.0-beta04.
        AAR metadata file: /Users/bs274/.gradle/caches/transforms-2/files-2.1/91eb0523894712d4b41398b97d9cc9e5/jetified-window-1.0.0-beta04/META-INF/com/android/build/gradle/aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.core:core-ktx:1.7.0.
        AAR metadata file: /Users/bs274/.gradle/caches/transforms-2/files-2.1/7479da060c34a75d66442cd7311187bd/jetified-core-ktx-1.7.0/META-INF/com/android/build/gradle/aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.core:core:1.7.0.
        AAR metadata file: /Users/bs274/.gradle/caches/transforms-2/files-2.1/9502e0b944d0afa38f1f881930b53324/core-1.7.0/META-INF/com/android/build/gradle/aar-metadata.properties.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s
Exception: Gradle task assembleDebug failed with exit code 1`

**Environment**
- Device/emulator being used: Samsung M21
- OS (iOS/ Android): Android 12
- Flutter version: 2.10.3

**Are you working on this issue? (Yes/No)**
yes

**Comment by AshAman999** [comment]
The issue #118 talks about it and the pr #119 handles the same i guess,

**Comment by AshAman999** [comment]
The issue #118 talks about it and the pr #119 handles the same i guess,

**Comment by AshAman999** [comment]
The issue #118 talks about it and the pr #119 handles the same i guess,

**Comment by nb9960** [comment]
Closing this as this is PR #119 fixes this.
