### ISSUE TITLE
Confirm password field box in signup page

### ISSUE THREAD

**Issue by AshAman999** [CCExtractor/beacon#154]
**Is your feature request related to a problem? Please describe.**
Like most authentication systems usually, there s a confirm password text field on the sign-up page, it's missing in this app.

**Describe the solution you'd like**
A second confirm password box would do the job that would show a toast if the password is a mismatch

**Describe alternatives you've considered**
Either we can simply show a toast on submit if the password was mismatched or it would show a red dot next to the password field if it's not matching that would turn green when the same password is in both the fields. Further minimizing the trouble for the end-users.

**Additional context**
Google's create account  section for reference, as the confirm password text field is there too
![image](https://user-images.githubusercontent.com/57723319/158047026-a783fcc5-4a02-4009-8fe9-5350226e5e8b.png)

**Are you working on this? (Yes/No)**
Yes

**Comment by AshAman999** [comment]
I have already done something like this in my previous app if possible plz assign this to me so I could start working on the same @nb9960

**Comment by cfsmp3** [comment]
I have to say I hate having to type the password twice :-) I very much prefer having an "eye" icon so I can see what I typed rather than typing the password blindly twice.

Also, while we are on the topic of passwords and signing in / signing up - I don't know if we've tested it with 1password and other password managers. Usually they just work, but it would be nice to confirm.

**Comment by nb9960** [comment]
I don't think secure-auth is much of a concern for such kind of application instead it might be a bit complicated from the user's point of view, using 1password would indeed be better. 
Still, will review the PR once you resolve the conflicts.
