### ISSUE TITLE
This line is misleading as a text field 

### ISSUE THREAD

**Issue by vik4114** [CCExtractor/beacon#158]
**Is your feature request related to a problem? Please describe.**
This line is misleading as a text field and if it is acting as a partition still it is not symmetric

**Screenshot**
![Screenshot_1647773488_1](https://user-images.githubusercontent.com/46121493/159159082-216564c3-fbb6-4b0b-beae-bd6e3e82919d.png)

**Describe the solution you'd like**
I think we should remove it

**Describe alternatives you've considered**
-Else we can make it symmetric
-Or Bring it just below the text field

**Additional context**
**Sol 1**                                   
![Screenshot_1647773488_2](https://user-images.githubusercontent.com/46121493/159159220-768a8f0d-b63c-4c43-8741-3534ae7968ce.png)  

 **Sol2**
![Screenshot_1647773488_3](https://user-images.githubusercontent.com/46121493/159159227-9ac9d63c-3a63-427a-af0e-25aa1debd3a5.png)

**Are you working on this? (Yes/No)**
Yes

**Comment by vik4114** [comment]
@nb9960 What do you think?

**Comment by ItsAdityaKSingh** [comment]
@vik4114 afaik that line is a mere partition between the two fields and is only for UI purposes. It has nothing to do with the textfields or symmetry. It's there to only get a general idea to users for where the divide lies between them.

**Comment by vik4114** [comment]
@ItsAdityaKSingh But without the line it looks good

**Comment by nb9960** [comment]
I guess the same follows for the other text fields too and because UI needs to be consistent, you'll have to make the changes throughout. 
Additionally, that line acted as a partition removing it doesn't look good, the latter one is still better (i.e, to add the line below the text field)

**Comment by srockstech** [comment]
@vik4114 Are you still working on this issue?

**Comment by vik4114** [comment]
@srockstech Yes, I was stuck with other work, I will raise pr soon.

**Comment by K1RA-16** [comment]
> @srockstech Yes, I was stuck with other work, I will raise pr soon.

Hi vik can i work on this if possible ??

**Comment by ItsAdityaKSingh** [comment]
Hey, @vik4114, are you working on resolving this?

**Comment by RohanSengupta326** [comment]
I think no one solved this issue, so I created a PR(#170). So please check. @ItsAdityaKSingh

**Comment by pnkr01** [comment]
is this issue resolved ?? 
@ItsAdityaKSingh
