### ISSUE TITLE
Misaligned Buttons on dialogue box.

### ISSUE THREAD

**Issue by Aadeesh11** [CCExtractor/beacon#16]
When you try to terminate a hike or logout, the yes/no buttons are misaligned.

How it is:
<img width="283" alt="Current" src="https://user-images.githubusercontent.com/66922161/147412430-6db7ea8c-f542-4f25-8b5b-348237b868fe.png"> 

How it can be: 
<img width="281" alt="Screenshot 2021-12-26 at 8 48 10 PM" src="https://user-images.githubusercontent.com/66922161/147412477-0ab8efe7-16da-4c74-9d96-bf0f6ee6784b.png">

I would like to work on this please assign it to me.

**Comment by nb9960** [comment]
Again, this is because constant values have been used in some places. Can you change all the constant parameters using [sizer](https://pub.dev/packages/sizer)?

**Comment by Aadeesh11** [comment]
Sure , will try to do it.
