### ISSUE TITLE
Auto refinement of email address enter by user

### ISSUE THREAD

**Issue by codewithkushagra** [CCExtractor/beacon#162]
**Describe the bug**
While logging, the redundancies in the Email Address string entered by the users are not filtered automatically by the app, for example if I enter "example@gmail.com " and the actual account is "example@gmail.com" the is shows user does not exist

**To Reproduce**

1. Go to Login Screen
2. Enter your email address with extra space at the end
3. Enter password and try to login
4. See error 'user does not exist'

**Expected behavior**
It should automatically refine such redundancies in the email string entered by the user. 

**Demonstration**

- I have left an extra space at the end
- It shows the error

![WhatsApp Image 2022-04-16 at 9 21 25 PM](https://user-images.githubusercontent.com/72088481/163682140-2f0ccf56-feab-43d7-b73e-0de36ba1f396.jpeg)

**Environment**
- Device/emulator being used: device version GM1911
- OS (iOS/ Android); If Android then android version: OS: 11
- Flutter version: 2.10.3

**Additional context**
The problem solution will improve the user experience.

**Are you working on this issue? (Yes/No)**
Yes

**Comment by codewithkushagra** [comment]
I want to work on this issue can you assign it to me

**Comment by HarshitGulgulia** [comment]
I have resolved the issue. I am making a PR.

**Comment by ItsAdityaKSingh** [comment]
@nb9960 This issue has been resolved :)

**Comment by ItsAdityaKSingh** [comment]
@codewithkushagra you may close this issue!
