### ISSUE TITLE
Misleading UI in login as guest page

### ISSUE THREAD

**Issue by codewithkushagra** [CCExtractor/beacon#165]
**Describe the bug**
When we login as guest and try to logout it, gives an option of create a new account and redirects us to auth screen. Instead it should show Logout which makes more sense.

**To Reproduce**

1. Login as guest
2. Try to logout
3. You get an option of create account
4. Redirects you to auth screen

**Expected behavior**
It should show logout option instead of create account option.

**Demonstration**

![WhatsApp Image 2022-04-17 at 5 05 17 PM](https://user-images.githubusercontent.com/72088481/163721649-5138a49d-eaba-414d-a3bc-f51b5d915701.jpeg)

**Environment**
- Device/emulator being used: oneplus 7 Pro
- OS (iOS/ Android); version 11.0.6.1, android 11
- Flutter version: 2.10.3

**Are you working on this issue? (Yes/No)**
yes

**Comment by codewithkushagra** [comment]
Can you please assign me this issue @nb9960

**Comment by nb9960** [comment]
Why do I need a logout button if I'm a guest? As far as I remember, this was discussed earlier on slack and @cfsmp3 suggested that we shouldn't have a logout button if the user is not logged in.

**Comment by codewithkushagra** [comment]
Actually the thing is, what if I already have an account and I signed in as a guest. If I wanna login from my old account it only gives the option of create a new account, maybe it should say something like go back to login page or something like that
