### ISSUE TITLE
i have forked and cloned the repo in env.example file value of google maps api key for android and ios is missing what should i do pls help

### ISSUE THREAD

**Issue by anmolkulshrestha** [CCExtractor/beacon#174]

**Comment by pnkr01** [comment]
Given example inside .env.example is 

ANDROID_MAP_API_KEY=<your_android_google_maps_api_key>
IOS_MAP_API_KEY=<your_ios_google_maps_api_key>
HTTP_ENDPOINT=<server's_HTTP_endpoint>(for example: https://beacon.aadibajpai.com/graphql)
WEBSOCKET_ENDPOINT=<server's_websocket_endpoint>(for example: wss://beacon.aadibajpai.com/subscriptions)


1. rename .env example to .env only


![image](https://user-images.githubusercontent.com/83778936/201536385-7ac77f8f-a07c-4dba-be40-5295b2c7b967.png)

2. go to https://console.cloud.google.com/ 
         -   sign in
         -   go to library 
         -   enable Map SDk for Android and for iOS
3. Go to credentials
   -      from the top create credential 
      ![image](https://user-images.githubusercontent.com/83778936/201536433-d6f5cb74-ef80-4652-a6f9-6a95e0b25638.png)
  -     copy the key and paste in the .env file


for 
HTTP_ENDPOINT=https://beacon.aadibajpai.com/graphql
WEBSOCKET_ENDPOINT=wss://beacon.aadibajpai.com/subscriptions

@anmolkulshrestha 

Use this, and after that, run the app; it will run. I'm also new here, and this may not be the best way to get started, but it gets the app running. I'll investigate further and learn more about this. There's also a great message for this doubt in Slack chat in #gsoc-beacon, answered by Aadeesh Oswal. I hope this helps.

**Comment by ItsAdityaKSingh** [comment]
Thanks @pnkr01 for the input!
The following env variables will not be working:
`HTTP_ENDPOINT=https://beacon.aadibajpai.com/graphql
WEBSOCKET_ENDPOINT=wss://beacon.aadibajpai.com/subscriptions`
@anmolkulshrestha, you need to run the beacon backend locally and put the variables you get using it. Rest is as usual. You will be able to run the app using it.

**Comment by ItsAdityaKSingh** [comment]
Closing the issue as not really one! Also, you could use [Slack](https://ccextractor.org/public/general/support/) channel to clarify doubts if any.
