### ISSUE TITLE
Remove deprecated primary property for Elevated Button

### ISSUE THREAD

**Issue by codeyuvraj** [CCExtractor/beacon#180]
**Describe the bug**
In hike_button.dart primary property is used for ElevatedButton

**To Reproduce**
Check line 27 in hike_button.dart

**Expected behavior**
No warning for using deprecated member

**Demonstration**
<img width="1128" alt="Screenshot 2023-02-07 at 9 36 04 PM" src="https://user-images.githubusercontent.com/40745610/217300323-10047a60-3ee2-4ff2-88a0-3138aa9bd667.png">

**Are you working on this issue? (Yes/No)**
Yes

**Comment by ItsAdityaKSingh** [comment]
Closing as resolved.
