### ISSUE TITLE
Having setup error in this Project

### ISSUE THREAD

**Issue by Debajyoti14** [CCExtractor/beacon#182]
![image](https://user-images.githubusercontent.com/91759192/218276621-d003b23c-0988-4606-bd4b-10fd78e8bbf4.png)

Facing this error while setting up the repo?
Can anyone help?

**Comment by bhav-khurana** [comment]
You can try switching the channel to the flutter stable channel

**Comment by Debajyoti14** [comment]
@bhav-khurana 
![image](https://user-images.githubusercontent.com/91759192/218295866-12fe16b7-206a-4f6b-835c-3a0276d0e6e6.png)
It's already in stable

**Comment by bhav-khurana** [comment]
then try `flutter pub upgrade` and `flutter upgrade`

**Comment by Debajyoti14** [comment]
![image](https://user-images.githubusercontent.com/91759192/218329863-d7bc5ee3-ff9f-4457-a4a4-aeebd3b26f9a.png)
@bhav-khurana Is this occurring as there's no API_KEY

**Comment by bhav-khurana** [comment]
I think yes ... try adding the API_KEY

**Comment by Debajyoti14** [comment]
@bhav-khurana From where i will get the API Key?😅

**Comment by Arnav2001** [comment]
I am also getting error in setting up this project. Do I need to lower my flutter or dart version. I am using 
Flutter 3.7.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9944297138 (11 days ago) • 2023-02-08 15:46:04 -0800
Engine • revision 248290d6d5
Tools • Dart 2.19.2 • DevTools 2.20.1

**Comment by bhav-khurana** [comment]
> @bhav-khurana From where i will get the API Key?😅

Ig you can dm the maintainer for that

**Comment by bhav-khurana** [comment]
> I am also getting error in setting up this project. Do I need to lower my flutter or dart version. I am using 
> Flutter 3.7.3 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision 9944297138 (11 days ago) • 2023-02-08 15:46:04 -0800
> Engine • revision 248290d6d5
> Tools • Dart 2.19.2 • DevTools 2.20.1

Did you add the API key?

**Comment by bhav-khurana** [comment]
> I am also getting error in setting up this project. Do I need to lower my flutter or dart version. I am using 
> Flutter 3.7.3 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision 9944297138 (11 days ago) • 2023-02-08 15:46:04 -0800
> Engine • revision 248290d6d5
> Tools • Dart 2.19.2 • DevTools 2.20.1

Did you add the API key?

**Comment by cfsmp3** [comment]
> May I know where is the contact information of maintainer to get API key

You need to get your own API key.

**Comment by Arnav2001** [comment]
I don't have google cloud console and I need to buy it is there any alternative to get free API key.

**Comment by cfsmp3** [comment]
> I don't have google cloud console and I need to buy it is there any alternative to get free API key.

https://blog.hubspot.com/website/google-maps-api
