### ISSUE TITLE
Exception: Invalid argument (scheduledDate): Must be a date in the future: Instance of 'TZDateTime' 

### ISSUE THREAD

**Issue by tanisha083** [CCExtractor/beacon#192]
**Describe the bug**
when you create a hike event this exception gets thrown. It's getting raised because the scheduled time is expected to be in future but it's not.
<img width="974" alt="image" src="https://user-images.githubusercontent.com/104641430/225733730-f6b20ec2-979d-4e15-9528-00e9cc90dcbb.png">

**Are you working on this issue? (Yes)**

**Comment by vkprogrammer-001** [comment]
If the issue is unassigned, may I take it up? Please allocate this issue to me.
