### ISSUE TITLE
Overlapping occurrence on Home

### ISSUE THREAD

**Issue by ItsAdityaKSingh** [CCExtractor/beacon#21]
### Buttons on home screen overlapping with the Tab below it. 
**The Issue is as shown:**

<img src="https://user-images.githubusercontent.com/69353350/147418851-32e50244-c301-471f-b1a7-9456f14b310f.png" height="500"/>

**It could be something like:**

<img src = "https://user-images.githubusercontent.com/69353350/147418841-a8062d10-8d0d-4909-9da2-69197c9f1a5e.png" height="500"/>

**Comment by ItsAdityaKSingh** [comment]
@nb9960 I would like to work on this issue.

**Comment by nb9960** [comment]
Isn't this somewhat related to #19? I mean adjusting all parameters using sizer should fix this too (most probably), if you have any other solution then do let me know.

**Comment by ItsAdityaKSingh** [comment]
Yes, surely. I too was open to using sizer but as mentioned in issue #25 , instead of implementing sizer once or twice to fix overflow couldn't we use it once and for all including padding, heights, etc. It would make the application's UI free from any sort of rendering issues. Also, always using MediaQuery could be prevented! Your views on this?

**Comment by nb9960** [comment]
Yes, this issue would be fixed by #19 and while fixing #25, so closing this.

**Comment by ItsAdityaKSingh** [comment]
Sure. That would do well!
