### ISSUE TITLE
Appearance of Sign In button

### ISSUE THREAD

**Issue by ItsAdityaKSingh** [CCExtractor/beacon#22]
## The SIGIN button for new users has a weird appearance. 
<img src="https://user-images.githubusercontent.com/69353350/147419010-dd2a5e4d-6331-42c6-85bc-af76e921fdb8.png" height="500"/>

- Instead of **SIGNIN** we can show it as **SIGN IN** 
- Also we could change the width of the button to make it look more pleasant.

**Comment by ItsAdityaKSingh** [comment]
If this issue seems genuine, could you assign it to me @nb9960 ?

**Comment by nb9960** [comment]
> * Also, we could change the button's width to make it look more pleasant.
UI needs to be consistent. Changing the sign-in button's width in one place would mean changing it everywhere possible.

Assigning it to you!
