### ISSUE TITLE
Offbeat Label and Hint Text

### ISSUE THREAD

**Issue by ItsAdityaKSingh** [CCExtractor/beacon#23]
#### The current 'Join a Hike' pop up has:

<img src="https://user-images.githubusercontent.com/69353350/147419204-942fd933-423a-4665-8373-050b9265252e.png" height="500"/>

- Black and Bold hint-text
- Weirdly sized **validate** button
- Too small label text

#### The current 'Create Hike' pop up has:

<img src="https://user-images.githubusercontent.com/69353350/147419252-cdf68bbf-1b95-4262-89fc-f844351cd314.png" height="500"/>

- Different colors of hint text for both fields

### We could change it to be more pleasant with our appflow by:
- Changing validate button formatting
- Assigning same text color and size to all the hint texts
- Increasing the text size of **Passkey** label text

**Comment by ItsAdityaKSingh** [comment]
@nb9960 I would like to work on these improvement issues. Could you assign them to me?

**Comment by nb9960** [comment]
Yes, text theme and button theme needs to be consistent throughout the application. I would suggest you to fix button theme throughout the app while working on #22 and text theme here.
Assigning it to you @ItsAdityaKSingh!

**Comment by ItsAdityaKSingh** [comment]
Yup, I'll do my best to take care of that. Thank You!
