### ISSUE TITLE
Incorrect Beacon Count Displayed in Group Card After Deletion and Creation of Beacons

### ISSUE THREAD

**Issue by vkprogrammer-001** [CCExtractor/beacon#230]
**Describe the bug**
The Beacon app is incorrectly displaying the total number of beacons in the group card. After deleting all beacons and creating new ones, the app is adding the count of the new beacons to the previous total, instead of updating the count to reflect the current number of beacons.

**To Reproduce**

1. Go to the 'Beacon' app.
2. Create a certain number of beacons (e.g., 44).
3. Delete a created beacon.
4. Create a new set of beacons (e.g., 4).
5. Check the total number of beacons displayed on the group card.

**Expected behavior**
The total number of beacons displayed on the group card should update to reflect the current number of beacons (e.g., 4), not the sum of the new and previously deleted beacons (e.g., 48).

**Demonstration**

https://github.com/CCExtractor/beacon/assets/143318563/d14f71a8-fb28-4186-b4ee-a8183704feb1

**Environment**
- Device/emulator being used: Pixel 3a
- OS (iOS/ Android); If Android then Android version: Android 13
- Flutter version:3.16.9

**Additional context**
This issue seems to be related to how the app is updating and displaying the total count of beacons. It's possible that the deletion of beacons is not being properly accounted for in the total count.

**Are you working on this issue? (Yes/No)**
yes I love to work on this issue

**Comment by RunTerror** [comment]
Hello @vkprogrammer-001 , I've actually resolved this issue in my PR (#227 ). I appreciate your understanding, and feel free to find another one to work on.
