### ISSUE TITLE
Marginal sizing improvements

### ISSUE THREAD

**Issue by ItsAdityaKSingh** [CCExtractor/beacon#25]
### Instead of using constants or MediaQuery sizing we could use sizer package for 
1. heights, 
2. widths, 
3. paddings, and
4. margins,

**It would improve simplicity of code and result in less overflow or overlapping errors in any screen size.**

**Comment by ItsAdityaKSingh** [comment]
I would like to work on this issue. @nb9960 could you please assign it to me?

**Comment by nb9960** [comment]
Sure, assigning it to you!

**Comment by Aadeesh11** [comment]
Device: Samsung M21. (branch : Main)

<img width="283" alt="Screenshot 2022-01-13 at 5 29 33 PM" src="https://user-images.githubusercontent.com/66922161/149326392-e162c543-0314-4d93-bdc8-5d17a836c94a.png">
<img width="279" alt="Screenshot 2022-01-13 at 5 30 56 PM" src="https://user-images.githubusercontent.com/66922161/149326598-2397bb70-c714-4729-8274-a3873c93940a.png">
<img width="281" alt="Screenshot 2022-01-13 at 5 31 20 PM" src="https://user-images.githubusercontent.com/66922161/149326662-799fa4d0-1689-4c40-8687-1bb4740a3e2f.png">
