### ISSUE TITLE
Maintain state when network connectivity is lost 

### ISSUE THREAD

**Issue by nb9960** [CCExtractor/beacon#3]
State of the Hike Screen shouldn't get affected when connectivity is lost. [Hive](https://pub.dev/packages/hive) has been used to store data in the local database so that when connectivity is lost, locally saved data can be consumed, but as of now, local data hasn't been used anywhere.

**Comment by KunjKanani** [comment]
@nb9960 I want to work on this issue.

**Comment by Manan2307** [comment]
Can I work on this? @nb9960

**Comment by Aadeesh11** [comment]
@Manan2307 are you still working on this?

**Comment by Manan2307** [comment]
No You can take it @Aadeesh11
