### ISSUE TITLE
Leader's name in nearby beacons is returned as null

### ISSUE THREAD

**Issue by ItsAdityaKSingh** [CCExtractor/beacon#35]
## Upon terminating the hike and coming back to home screen, my own beacon is shown as Anonymous.

<p align="center">
<img src="https://user-images.githubusercontent.com/69353350/147506133-374e1dbf-0847-49b7-9a90-b6eafe998b98.png" height="500"/>  <img src="https://user-images.githubusercontent.com/69353350/147506130-253a412c-3ffc-4422-97e9-35f97ca4f36e.png" height="500"/> 

</p>

Is this a bug or it is supposed to work this way?

**Also note the difference of top-padding between the two columns**

**Comment by ItsAdityaKSingh** [comment]
If it's a genuine bug, or the mechanism needs to be different, I would like to work upon it @nb9960 .

**Comment by nb9960** [comment]
This is because nearbyBeacons query in the backend gives out null as the leader's name. You can confirm this [here](https://beacon.aadibajpai.com/graphql).
For padding related issues, it would be better if you could fix it with other UI oriented issues

**Comment by ItsAdityaKSingh** [comment]
Ok, thanks for clarifying. I would surely look into it. 
The padding issue has been fixed in PR #45

**Comment by Aadeesh11** [comment]
The changes made to backend repo have not been deployed yet. To test, setup the backend locally after forking the backend repo.
