### ISSUE TITLE
Expired Beacons

### ISSUE THREAD

**Issue by ItsAdityaKSingh** [CCExtractor/beacon#37]
### Shouldn't my expired beacons be showing 'EXPIRED' instead of remaining switched on upon passing given duration and asking me to terminate it again?

<img src="https://user-images.githubusercontent.com/69353350/147506671-b006f56f-ddfc-4f0e-b635-a94ae21a6698.png" height="500"/>

***Notice the expiry time.***

**Comment by ItsAdityaKSingh** [comment]
If my issue is genuine here, then I would like to work upon it @nb9960 .

**Comment by Aadeesh11** [comment]
> If my issue is genuine here, then I would like to work upon it @nb9960 .

#33 will fix this 😅 mostly.

**Comment by ItsAdityaKSingh** [comment]
Voila! Closing this issue then.
