### ISSUE TITLE
Existing and New Users input errors connected

### ISSUE THREAD

**Issue by ItsAdityaKSingh** [CCExtractor/beacon#44]
## Upon running into an error on the Existing Users screen or New Users screen, the other screen starts showing an error message too.

https://user-images.githubusercontent.com/69353350/147579381-42c57141-22d4-4455-b5d6-3a6d81fdf0a3.mov

**Comment by nb9960** [comment]
PR #30 will handle this. I've mentioned this issue there, didn't look into this earlier
