### ISSUE TITLE
[Tests]: Write Test for beacon project.

### ISSUE THREAD

**Issue by devansh12b2** [CCExtractor/beacon#46]
The following architecture needs to be followed while writing tests: 
- model_tests
- service_tests
- widget_tests
- viewmodel_tests 

- [ ]  Login Screen
- [ ] Home page
- [ ] beacon_card.dart
- [ ] create_join_dialog.dart
- [ ] dialog_boxes.dart
- [ ] hike_button.dart
- [ ] hike_screen_widget.dart
- [ ] shape_painter.dart

For the Hike screen, MVVM architecture isn't followed so I am creating an issue for refactoring it, once it's done then tests can be added for that screen too.

Feel free to add/suggest anything that you think is missing.

**Comment by devansh12b2** [comment]
I will like to work on 1 of these.

**Comment by Aadeesh11** [comment]
I would also like to write tests for a screen.

**Comment by ItsAdityaKSingh** [comment]
I too would like to work on writing these tests!

**Comment by nb9960** [comment]
Edited the above list, feel free to comment here for the specific widget/screen/model/query/mutation you want to work on (you can add to the list too), will assign you by mentioning there. But remember only one particular task at a time :)

@devansh12b2 @Aadeesh11 @ItsAdityaKSingh @Literal-Eval
