### ISSUE TITLE
Adding tests

### ISSUE THREAD

**Issue by Literal-Eval** [CCExtractor/beacon#47]
lib/components

- [ ] beacon_card.dart
- [ ] create_join_dialog.dart
- [ ] dialog_boxes.dart
- [ ] hike_button.dart
- [ ] hike_screen_widget.dart
- [ ] shape_painter.dart

Assign some of these to me.

**Comment by ItsAdityaKSingh** [comment]
There's already issue #46 with the same purpose. If possible could you add these tasks there instead of creating a new one for easy referencing?
