### ISSUE TITLE
Feature: Reminder for a pre-scheduled hike 

### ISSUE THREAD

**Issue by ItsAdityaKSingh** [CCExtractor/beacon#52]
After issue #5 is addressed we could further enhance it by **allowing other users to pin a scheduled hike**.
We could also give them **notifications beforehand, on some set timers (say like 24 hours before -> 12 hours before -> 1 hour before)**, to be able to join the hike on time!

**Comment by ItsAdityaKSingh** [comment]
If this feature seems to be valid, I would like to work on it @nb9960

**Comment by nb9960** [comment]
Prescheduling the beacon is handled in #53 along with joining the pre-scheduled beacon, and notification is thrown when the beacon starts. Not sure if we still need this but still, it's open for discussion

**Comment by ItsAdityaKSingh** [comment]
In #53, a notification is displayed when the hike has started. One can be notified and reminded at a certain time interval earlier too if one forgets about it.
