### ISSUE TITLE
Forgot password option

### ISSUE THREAD

**Issue by ItsAdityaKSingh** [CCExtractor/beacon#56]
There's no **forget password** option on the login screen or a way to retrieve a forgotten password of one's account. This makes it really difficult for a user to log in once the password is forgotten.

**Comment by ItsAdityaKSingh** [comment]
@nb9960 Could I work on introducing this feature?

**Comment by nb9960** [comment]
I doubt if backend is ready for this

**Comment by ItsAdityaKSingh** [comment]
Yes, @nb9960. I went through the backend and did not find any such functionality. So should I be closing this issue or keep it open for future references and improvements after work is done in the backend?

**Comment by nb9960** [comment]
Closing this issue for now.
