### ISSUE TITLE
Refactor the Hike screen to follow stacked MVVM architecture.

### ISSUE THREAD

**Issue by Aadeesh11** [CCExtractor/beacon#57]
It would be better to add this entire function in the Hike screen view model (which I guess isn't being used right now). So maybe create a new issue to refactor the Hike screen to make it more readable.

_Originally posted by @nb9960 in https://github.com/CCExtractor/beacon/pull/51#discussion_r780778058_

I would like to work on this, please assign it to me.

**Comment by Aadeesh11** [comment]
@nb9960 do we need to refractor it to follow mvvm structure or just refractor it to make it more readable?

**Comment by nb9960** [comment]
> @nb9960 do we need to refractor it to follow mvvm structure or just refractor it to make it more readable?

Both. It needs to follow MVVM architecture as well as it should be readable.
