### ISSUE TITLE
Share route if beacon is active

### ISSUE THREAD

**Issue by nb9960** [CCExtractor/beacon#6]
Whenever a new location is fetched from `beaconLocation` subscription, it gets stored in the route list. This can be used to share route if the beacon is active.

**Comment by Aadeesh11** [comment]
I would like to work on this, please assign this to me.
Also how should route be shared, for eg: through a screenshot of the map maybe?

**Comment by nb9960** [comment]
Screenshot along with other necessary details like starting and current location
