### ISSUE TITLE
Registered Users Signing up

### ISSUE THREAD

**Issue by ItsAdityaKSingh** [CCExtractor/beacon#60]
Registered users, upon signing up, receive a message saying "**Something went wrong**"

Instead, they can be informed that they are already registered and should try logging in instead of signing up again.

### Screenshot for details:

<img src="https://user-images.githubusercontent.com/69353350/149220264-5fc8ef67-0ae2-407e-9b49-7993a05c350c.png" height="500"/>

**Are you working on this issue**
Yes

**Comment by Shashwat2708** [comment]
I can help with this issue.
I would love to be assigned to this issue as this can create a misunderstanding in the users mind whether it is the app or their internet.
