### ISSUE TITLE
Overlapping of buttons on home screen.

### ISSUE THREAD

**Issue by noman2002** [CCExtractor/beacon#71]
Create hike and join hike button are getting overlapped on hike screen.
<img src="https://user-images.githubusercontent.com/54404474/150165286-935e2362-2cea-4d8d-8cc7-e71ff24ab77c.png" height="550" width="250" />

**Comment by noman2002** [comment]
Please assign it to me. I am working on it.

**Comment by ItsAdityaKSingh** [comment]
@noman2002 Which emulator are you using? Have you fetched all the latest commits on the main branch?

**Comment by noman2002** [comment]
@ItsAdityaKSingh I'm using pixel 4a. I have fetched all the commits but Your PR is not merged in the main branch.

**Comment by ItsAdityaKSingh** [comment]
Thanks for confirming! You would like to check #63 as it would also fix the mentioned issue!

**Comment by nb9960** [comment]
@noman2002 Feel free to reopen this issue if the issue still persists
