### ISSUE TITLE
The plugin geocoder uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by MabudAlam** [CCExtractor/beacon#78]
**Describe the bug**
The plugin `geocoder` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**To Reproduce**
Compiling the app
![e1](https://user-images.githubusercontent.com/47685150/150589195-efab7ca0-6142-4175-aff0-8c3c7f29f55f.png)

**Expected behavior**
geocoder should be replaced with [geocoder2 1.0.0 ](https://pub.dev/packages/geocoder2/install) or [geocode 1.0.1 ](https://pub.dev/packages/geocode)

**Environment**
- Device/emulator being used: <Android 10/Pixel 2 Xl>
- OS (iOS/ Android); If Android then android version: <Android: 10>
- Flutter version: <2.8>

**Are you working on this issue? (Yes/No)**
Yes, Please assign me this issue.

**Comment by Aadeesh11** [comment]
None of geocoder2 1.0.0 or geocode 1.0.1 provide "local" geocoding.

**Comment by Pavel401** [comment]
> None of geocoder2 1.0.0 or geocode 1.0.1 provide "local" geocoding.

Yeah,but I found https://github.com/nguyenxdat/flutter_geocoder  this.It has null safty.
