### ISSUE TITLE
Only Capital Passkey Values allowed

### ISSUE THREAD

**Issue by ItsAdityaKSingh** [CCExtractor/beacon#79]
**Describe the bug**
Only capital Passkey values are allowed. Users can't enter passkey in small cases even if the passkey's right.

**To Reproduce**

1. Go to 'HomeScreen'
2. Click on 'Join a Hike'
3. Enter a passkey in small case

**Expected behavior**
User should be able to enter the hike with the right passkey, irrespective of upper or small case entered.

**Demonstration**

https://user-images.githubusercontent.com/69353350/150589761-ba8fb45f-b4ff-408d-88d9-f03efedf3131.mov

**Environment**
- Device/emulator being used: Pixel 4XL
- OS (iOS/ Android); If Android then android version: <OS: 10>
- Flutter version: 2.8.1

**Are you working on this issue? (Yes/No)**
Yes, I am working on this issue

**Comment by Aadeesh11** [comment]
Backend only generates passkeys which have capital alphabets in them.

**Comment by ItsAdityaKSingh** [comment]
We could make it simple for users by capitalizing our input in-app only.
