### ISSUE TITLE
the 'minutes' is not showing properly when selecting time. So proper minutes can't be set. 

### ISSUE THREAD

**Issue by RohanSengupta326** [CCExtractor/beacon#92]
<img src="https://user-images.githubusercontent.com/64458868/150766437-c92e6122-b04c-4492-872f-bf562de492dd.jpeg" width="24%" />

**Comment by RohanSengupta326** [comment]
No, I am not @ItsAdityaKSingh

**Comment by ItsAdityaKSingh** [comment]
Thanks for notifying @RohanSengupta326. I would work on resolving the issue. Could you confirm on which device was this issue noticed?

**Comment by RohanSengupta326** [comment]
@ItsAdityaKSingh, I used a physical device(Android, Samsung Galaxy A7).

**Comment by ItsAdityaKSingh** [comment]
@RohanSengupta326 Could you test PR #93 and check if the problem persists?

**Comment by nb9960** [comment]
I don't think this issue is caused due to the theme of the dialog box or text size. So PR #93 may not fix this. This seems to be more of a device or package related issue.

**Comment by ItsAdityaKSingh** [comment]
Yup, I checked it on various screen sizes and did not get any error. But looking into this issue, I tried solving it by reducing font size for time fields.
